export const EMPTY_SCREEN = {
  CONNECTORS: {
    IMG_NAME: 'connector.png',
    TITLE_SEARCH: 'No search results found',
    DESC_SEARCH: 'We couldn’t find the connector you are looking for',
    TITLE_SEARCH_CONTENT: 'No search results found',
    DESC_SEARCH_CONTENT: 'We couldn’t find the content you are looking for',
  },
  ANALYTICS: {
    IMG_NAME: 'experiments.png',
    TITLE: 'You haven’t added any experiments yet!',
    DESC: 'Experiments is the best way to test multiple search configuration variants and pick the best one that fulfills business needs. SearchAssist allows you to create experiments with two or more variants to continuously improve search relevance and user experience.',
    TITLE_SEARCH: 'No search results found',
    DESC_SEARCH: 'We couldn’t find the experiment you are looking for',
  },
  MANAGE: {
    IMG_NAME: 'no-content.png',
    TITLE_SEARCH_CHANNELS: 'No search results found',
    DESC_SEARCH_CHANNELS: 'We couldn’t find the channel you are looking for',
  },
  MANAGE_CREDENTIALS: {
    IMG_NAME: 'credentials.png',
    TITLE: 'You haven’t configured any credentials yet!',
    DESC: 'Rule is powerful tool to personalize and fine-tune search results. SearchAssist allows you to define rules based on Search , Page and User-contexts. Rules can also be used for merchandising and promotions.',
    TITLE_SEARCH: 'No search results found',
    DESC_SEARCH: 'We couldn’t find the credentials you are looking for',
  },
  MANAGE_TEAM: {
    IMG_NAME: 'team.png',
    TITLE_SEARCH: 'No results found',
    DESC_SEARCH: 'You have no listed Teams! Let’s change it...',
  },
  MANAGE_ORDERS_INVOICES: {
    IMG_NAME: 'search-insight.png',
    TITLE: 'No invoice log available',
    DESC: 'After subscribing to any of the plans offered, your invoices will appear here',
  },
  MANAGE_USAGE_LOGS: {
    IMG_NAME: 'contract-message.png',
    TITLE: 'No usage log available',
    DESC: 'After subscribing to any of the plans offered, your invoices will appear here',
    TITLE_SEARCH: 'No results found',
    DESC_SEARCH: 'You have no listed Teams! Let’s change it...',
  },
  CONTEXTUAL_RULES: {
    IMG_NAME: 'business-rules.png',
    TITLE: 'No Contextual Rules Found',
    DESC: 'Contextual Rules allows you to define outcomes based on various conditions <br> set by you on search context or Page context or the User context. <br> These rules are can help achieve personalization of search results for your end users. <br> Not sure what are Contextual rules? Visit our <a href="https://docs.kore.ai/searchassist/concepts/personalizing-results/personalizing-results-ranking/#Configuring_Business_Rules" target="blank">Support <i class="si-external-horizantal"></i></a>',
    TITLE_SEARCH: 'No results found',
    DESC_SEARCH: 'To adjusting your search to find what you’re looking for.',
  },
  NLP_RULES: {
    IMG_NAME: 'business-rules.png',
    TITLE: 'No NLP Rules Found',
    DESC: 'Try adding NLP rules to find what you are looking for <br> Not sure what are Contextual rules? Visit our <a href="https://docs.kore.ai/searchassist/concepts/personalizing-results/personalizing-results-ranking/#Configuring_Business_Rules" target="blank">Support <i class="si-external-horizantal"></i></a>',
    TITLE_SEARCH: 'No results found',
    DESC_SEARCH: 'To adjusting your search to find what you’re looking for.',
  },
  INDICES_FIELD: {
    IMG_NAME: 'field.png',
    TITLE_SEARCH_FIELD: 'No search results found',
    DESC_SEARCH_FIELD: 'We couldn’t find the index fields you are looking for',
  },
  INDICES_TRAITS: {
    IMG_NAME: 'traits.png',
    TITLE: 'You haven’t added any traits yet!',
    DESC: 'Traits are specific entities, attributes or details that the users express in their conversations. Traits present in the utterance can be used in driving the intent detection and bot conversation flows. SearchAssist allows you to define Traits and train the utterances.',
    TITLE_SEARCH: 'No search results found',
    DESC_SEARCH: 'We couldn’t find what you are looking for',
  },
  INDICES_SYNONYMS: {
    IMG_NAME: 'synonyms.png',
    TITLE: 'You have not added any synonyms yet!',
    DESC: 'Synonyms are a set of equivalent words that are considered to expand search queries to improve findability. SearchAssist allows you to define synonym & one-way synonym.',
    TITLE_SEARCH: 'No search results found',
    DESC_SEARCH: 'We couldn’t find what you are looking for',
  },
  INDICES_WORKBENCH: {
    IMG_NAME: 'sammy-steps.png',
    TITLE: 'No Stages Added!',
    DESC: 'Transform the incoming data into optimized documents using Index Pipeline Stages.',
  },
  RESULT_RANKING: {
    IMG_NAME: 'result-ranking.png',
    TITLE: 'You haven’t added any queries yet!',
    DESC: 'Results Ranking is an interactive and visual way to tune results. SearchAssist allows you to preview and customize the search results as per the business needs',
    TITLE_SEARCH: 'No search results found',
    DESC_SEARCH: 'We couldn’t find what you are looking for',
  },
};
